// cmd/seed_nuzlocke seeds the Nuzlocke reference timeline — locations with
// their encounter pools, bosses with their squads/movesets/level caps — from a
// seed file such as seeds/nuzlocke_platinum.json.
//
// ── The seed file is maintained research data ──
//
// It used to be generated by scripts/extract_nuzlocke_seed.js from the design
// prototype (docs/design/hunt-prototype.dc.html), and this file used to say
// "never hand-edit, re-run the extractor instead". That contract is retired.
// The prototype only ever mocked the first thirteen stops — up to Gym 2 — and
// its encounter pools were drawn to look plausible in a mockup rather than to
// match the game: it put Geodude in Ravaged Path (Diamond/Pearl only), gave
// Eterna Forest four species where Platinum has eleven, and left Kricketot off
// Route 201. A timeline that covers a whole game cannot come from a mockup, so
// the file is now hand-maintained and the extractor is history.
//
// ── What the file carries, and what this tool derives ──
//
// The file carries only what a human researched from Bulbapedia/Serebii: the
// story order, trainer rosters as species NAMES with levels and abilities, and
// move NAMES. Everything mechanical is resolved here against the database:
//
//   - species name  -> pokemon.id
//   - move name     -> moves.type, moves.power, moves.damage_class
//   - location area -> the encounter pool, from pokemon_locations
//
// This is deliberate. A dex id or a move's base power written by hand in JSON
// is a fact that can be wrong and that nothing will ever check; resolved from
// the tables the rest of the app already trusts, it cannot drift. An unknown
// name is a hard failure, not a skipped row — a typo must not seed a hole.
//
// ── Idempotence ──
//
// Timeline entries are upserted on (game_id, version, slug) and never
// truncated, so timeline_entry_id stays stable across re-seeds:
// nuzlocke_encounters_logged and nuzlocke_boss_progress reference it and must
// not be orphaned (see migrations/013_add_nuzlocke.sql). A location's pool and
// a boss's squad are fully owned children of one entry with no identity of
// their own, so those are replaced in full under the entry's stable id.
package main

import (
	"context"
	"encoding/json"
	"log"
	"os"
	"strings"

	"github.com/casper/shinytracker/internal/database"
	"github.com/joho/godotenv"
)

type seedFile struct {
	Game string `json:"game"`
	// Which version of a multi-version games row this timeline describes —
	// 'platinum', 'diamond', … Required: games.id 5 is
	// "Diamond/Pearl/Platinum" and the three disagree about routes and
	// trainers alike (migration 017).
	Version string      `json:"version"`
	Entries []seedEntry `json:"entries"`
}

type seedEntry struct {
	Slug      string  `json:"slug"`
	Kind      string  `json:"kind"` // "location" or "boss"
	SortOrder int     `json:"sort_order"`
	Name      string  `json:"name"`
	Place     *string `json:"place"`
	BossTitle *string `json:"boss_title"`
	LevelCap  *int    `json:"level_cap"`

	// Location only. `areas` are pokemon_locations.area slugs whose wild
	// encounter tables make up this stop's pool; `encounters` names species to
	// add on top, for the things no wild table holds — the starter choice, a
	// gift, or a static like the Friday Drifloon at Valley Windworks.
	Areas      []string `json:"areas"`
	Encounters []string `json:"encounters"`

	Squad []seedBossMon `json:"squad"` // boss only
}

type seedBossMon struct {
	Species   string   `json:"species"`
	Level     int      `json:"level"`
	Ability   string   `json:"ability"`
	SortOrder int      `json:"sort_order"`
	Moves     []string `json:"moves"`
}

var validKinds = map[string]bool{"location": true, "boss": true}

// gen4MoveNames maps the Generation IV in-game spellings a Bulbapedia/Serebii
// roster uses onto the modern names in the `moves` table. Sourced from the
// research pass, which flagged every one of these itself.
var gen4MoveNames = map[string]string{
	"faint attack": "Feint Attack",
	"solarbeam":    "Solar Beam",
	"thunderpunch": "Thunder Punch",
	"extremespeed": "Extreme Speed",
	"smokescreen":  "Smokescreen",
	"grasswhistle": "Grass Whistle",
	"bubblebeam":   "Bubble Beam",
	"vicegrip":     "Vice Grip",
	"sand-attack":  "Sand Attack",
	"featherdance": "Feather Dance",
	"poisonpowder": "Poison Powder",
	"thundershock": "Thunder Shock",
	"dynamicpunch": "Dynamic Punch",
	"doubleslap":   "Double Slap",
	"selfdestruct": "Self-Destruct",
	"softboiled":   "Soft-Boiled",
	"mud-slap":     "Mud-Slap",
	"will-o-wisp":  "Will-O-Wisp",
	"double-edge":  "Double-Edge",
	"lock-on":      "Lock-On",
	"u-turn":       "U-turn",
	"x-scissor":    "X-Scissor",
	"hi jump kick": "High Jump Kick",
	"ancientpower": "Ancient Power",
	"mr. mime":     "Mr. Mime",
}

// resolvedMove is a move name turned into the three columns the client needs.
type resolvedMove struct {
	name        string
	moveType    string
	power       int
	damageClass string
}

func main() {
	_ = godotenv.Load()

	if err := database.ConnectDB(); err != nil {
		log.Fatal("Failed to connect to database:", err)
	}
	defer database.CloseDB()

	seedPath := "seeds/nuzlocke_platinum.json"
	if len(os.Args) > 1 {
		seedPath = os.Args[1]
	}

	data, err := os.ReadFile(seedPath)
	if err != nil {
		log.Fatalf("Failed to read %s: %v", seedPath, err)
	}
	var sf seedFile
	if err := json.Unmarshal(data, &sf); err != nil {
		log.Fatalf("JSON parse error in %s: %v", seedPath, err)
	}
	if strings.TrimSpace(sf.Version) == "" {
		log.Fatalf("%s is missing its top-level \"version\" (e.g. \"platinum\")", seedPath)
	}

	ctx := context.Background()

	var gameID int
	if err := database.DB.QueryRow(ctx, "SELECT id FROM games WHERE title = $1", sf.Game).Scan(&gameID); err != nil {
		log.Fatalf("Failed to find game %q: %v", sf.Game, err)
	}

	currentSlugs := make([]string, 0, len(sf.Entries))
	pooled, squadded := 0, 0
	for _, e := range sf.Entries {
		if !validKinds[e.Kind] {
			log.Fatalf("Entry %q has invalid kind %q (must be location or boss)", e.Slug, e.Kind)
		}
		if e.Slug == "" {
			log.Fatalf("Entry %q is missing its stable slug", e.Name)
		}

		var entryID int
		err := database.DB.QueryRow(ctx,
			`INSERT INTO nuzlocke_timeline_entries (game_id, version, slug, kind, name, sort_order, place, boss_title, level_cap)
			 VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
			 ON CONFLICT (game_id, version, slug) DO UPDATE SET
			     kind = EXCLUDED.kind,
			     name = EXCLUDED.name,
			     sort_order = EXCLUDED.sort_order,
			     place = EXCLUDED.place,
			     boss_title = EXCLUDED.boss_title,
			     level_cap = EXCLUDED.level_cap
			 RETURNING id`,
			gameID, sf.Version, e.Slug, e.Kind, e.Name, e.SortOrder, e.Place, e.BossTitle, e.LevelCap,
		).Scan(&entryID)
		if err != nil {
			log.Fatalf("Failed to upsert timeline entry %q: %v", e.Slug, err)
		}
		currentSlugs = append(currentSlugs, e.Slug)

		switch e.Kind {
		case "location":
			pooled += seedEncounterPool(ctx, gameID, sf.Version, entryID, e)
		case "boss":
			squadded += seedBossSquad(ctx, entryID, e)
		}
	}

	pruneRemovedEntries(ctx, gameID, sf.Version, currentSlugs)

	log.Printf("Seeded %d %s timeline entries for %q: %d pool rows, %d squad members.",
		len(sf.Entries), sf.Version, sf.Game, pooled, squadded)
}

// derivePool reads a location's encounter pool out of pokemon_locations.
//
// Grass only, and only the default state of the world: Poké Radar, swarms, GBA
// dual-slot, honey trees, the Great Marsh's daily rotation and post-National-
// Dex additions are all excluded, because none of them is what a player walking
// a route for the first time can encounter. Time-of-day rows ARE included — a
// route's night table is still that route's table.
//
// Three of those condition families are PAIRS, where one member is the default
// state and only the other is special: `slot2-none`, `backlot-not-mentioned`
// (Trophy Garden before the story flag) and `story-progress-before-national-dex`
// are the baseline and must survive the filter. Sweeping a whole family out with
// a bare LIKE drops real encounters and leaves a *non-empty* pool, so the
// empty-pool guard below never fires and the loss is invisible — the exact
// silent-hole failure this tool is built to make impossible.
//
// Verified against the three stops whose hand-made pools were known to be
// right: Route 202, Oreburgh Gate and Oreburgh Mine come back exact.
func derivePool(ctx context.Context, gameID int, version string, areas []string) []int {
	if len(areas) == 0 {
		return nil
	}
	rows, err := database.DB.Query(ctx,
		`SELECT DISTINCT l.pokemon_id
		 FROM pokemon_locations l
		 WHERE l.game_id = $1 AND l.version = $2 AND l.area = ANY($3) AND l.terrain = 'grass'
		   AND NOT EXISTS (
		       SELECT 1 FROM unnest(l.conditions) c
		       WHERE c = 'radar-on' OR c = 'swarm-yes'
		          OR c LIKE 'honey-tree-%' OR c LIKE 'great-marsh-daily-slot-%'
		          OR (c LIKE 'slot2-%' AND c <> 'slot2-none')
		          OR (c LIKE 'backlot-%' AND c <> 'backlot-not-mentioned')
		          OR (c LIKE 'story-progress-%national-dex%'
		              AND c <> 'story-progress-before-national-dex')
		   )
		 ORDER BY l.pokemon_id`, gameID, version, areas)
	if err != nil {
		log.Fatalf("Failed to derive encounter pool from areas %v: %v", areas, err)
	}
	defer rows.Close()

	var ids []int
	for rows.Next() {
		var id int
		if err := rows.Scan(&id); err != nil {
			log.Fatalf("Failed to scan derived pool row: %v", err)
		}
		ids = append(ids, id)
	}
	if len(ids) == 0 {
		log.Fatalf("Areas %v produced no %s encounters — check the area slugs against pokemon_locations", areas, version)
	}
	return ids
}

// seedEncounterPool replaces the full encounter pool for one location entry:
// everything its areas yield, plus any explicitly named species. Full
// delete+reinsert under the entry's stable id — the pool has no identity of its
// own outside the entry it belongs to.
func seedEncounterPool(ctx context.Context, gameID int, version string, entryID int, e seedEntry) int {
	ids := derivePool(ctx, gameID, version, e.Areas)
	seen := make(map[int]bool, len(ids)+len(e.Encounters))
	for _, id := range ids {
		seen[id] = true
	}
	for _, name := range e.Encounters {
		id := resolveSpecies(ctx, name, e.Slug)
		if !seen[id] {
			seen[id] = true
			ids = append(ids, id)
		}
	}
	if len(ids) == 0 {
		log.Fatalf("Location %q has neither areas nor encounters", e.Slug)
	}

	if _, err := database.DB.Exec(ctx, `DELETE FROM nuzlocke_encounter_pool WHERE timeline_entry_id = $1`, entryID); err != nil {
		log.Fatalf("Failed to clear encounter pool for %q: %v", e.Slug, err)
	}
	for i, pokemonID := range ids {
		if _, err := database.DB.Exec(ctx,
			`INSERT INTO nuzlocke_encounter_pool (timeline_entry_id, pokemon_id, sort_order) VALUES ($1, $2, $3)`,
			entryID, pokemonID, i+1,
		); err != nil {
			log.Fatalf("Failed to insert encounter pool row for %q (pokemon %d): %v", e.Slug, pokemonID, err)
		}
	}
	return len(ids)
}

// resolveSpecies turns a species name into pokemon.id. A miss is fatal: a
// silently skipped species is a hole in a route's pool that nothing downstream
// can detect.
func resolveSpecies(ctx context.Context, name, slug string) int {
	var id int
	if err := database.DB.QueryRow(ctx,
		`SELECT id FROM pokemon WHERE lower(name) = lower($1)`, strings.TrimSpace(name)).Scan(&id); err != nil {
		log.Fatalf("Unknown species %q in entry %q: %v", name, slug, err)
	}
	return id
}

// resolveMove turns a move name into the type, power and damage class the
// client renders and reasons about, applying the Gen IV spelling map first.
//
// power is COALESCEd to 0 because nuzlocke_boss_moves.power is NOT NULL — but
// note that 0 there does NOT mean "harmless": moves.power is NULL for every
// variable-power damaging move (Grass Knot, Metal Burst, Dragon Rage). That is
// exactly why damage_class is stored alongside it and is what the client's
// coverage warning keys off.
func resolveMove(ctx context.Context, name, slug string) resolvedMove {
	lookup := strings.TrimSpace(name)
	if modern, ok := gen4MoveNames[strings.ToLower(lookup)]; ok {
		lookup = modern
	}
	var mv resolvedMove
	if err := database.DB.QueryRow(ctx,
		`SELECT name, type, COALESCE(power, 0), damage_class
		 FROM moves WHERE lower(name) = lower($1) LIMIT 1`, lookup,
	).Scan(&mv.name, &mv.moveType, &mv.power, &mv.damageClass); err != nil {
		log.Fatalf("Unknown move %q (looked up as %q) in entry %q: %v", name, lookup, slug, err)
	}
	return mv
}

// seedBossSquad replaces a boss's full squad and movesets. Same
// delete+reinsert rationale as seedEncounterPool; boss_moves cascades off
// boss_pokemon so clearing the squad clears its moves too.
func seedBossSquad(ctx context.Context, entryID int, e seedEntry) int {
	if _, err := database.DB.Exec(ctx, `DELETE FROM nuzlocke_boss_pokemon WHERE timeline_entry_id = $1`, entryID); err != nil {
		log.Fatalf("Failed to clear boss squad for %q: %v", e.Slug, err)
	}
	for _, sq := range e.Squad {
		pokemonID := resolveSpecies(ctx, sq.Species, e.Slug)
		var bossPokemonID int
		if err := database.DB.QueryRow(ctx,
			`INSERT INTO nuzlocke_boss_pokemon (timeline_entry_id, pokemon_id, level, ability, sort_order)
			 VALUES ($1, $2, $3, $4, $5) RETURNING id`,
			entryID, pokemonID, sq.Level, sq.Ability, sq.SortOrder,
		).Scan(&bossPokemonID); err != nil {
			log.Fatalf("Failed to insert boss squad member for %q (%s): %v", e.Slug, sq.Species, err)
		}
		for i, moveName := range sq.Moves {
			mv := resolveMove(ctx, moveName, e.Slug)
			if _, err := database.DB.Exec(ctx,
				`INSERT INTO nuzlocke_boss_moves (boss_pokemon_id, name, type, power, damage_class, sort_order)
				 VALUES ($1, $2, $3, $4, $5, $6)`,
				bossPokemonID, mv.name, mv.moveType, mv.power, mv.damageClass, i+1,
			); err != nil {
				log.Fatalf("Failed to insert boss move %q for %q: %v", moveName, e.Slug, err)
			}
		}
	}
	return len(e.Squad)
}

// pruneRemovedEntries deletes any timeline entry for this game AND version
// whose slug is no longer present in the seed file. Scoped by version so
// seeding Platinum can never delete Diamond's timeline.
//
// Mirrors cmd/seed's pruneRemovedMethods: nuzlocke_timeline_entries is no
// longer truncated each run, so a row dropped from the JSON would otherwise
// linger forever. Any nuzlocke_encounters_logged/nuzlocke_boss_progress row
// pointing at it is SET NULL (migrations/013_add_nuzlocke.sql), not deleted, so
// this can never destroy a user's run — but it is logged loudly all the same.
func pruneRemovedEntries(ctx context.Context, gameID int, version string, currentSlugs []string) {
	rows, err := database.DB.Query(ctx,
		`SELECT id, slug, name FROM nuzlocke_timeline_entries
		 WHERE game_id = $1 AND version = $2 AND NOT (slug = ANY($3))`,
		gameID, version, currentSlugs)
	if err != nil {
		log.Fatal("Failed to query stale nuzlocke_timeline_entries: ", err)
	}
	type stale struct {
		id   int
		slug string
		name string
	}
	var staleRows []stale
	for rows.Next() {
		var s stale
		if err := rows.Scan(&s.id, &s.slug, &s.name); err != nil {
			rows.Close()
			log.Fatal("Failed to scan stale nuzlocke_timeline_entries: ", err)
		}
		staleRows = append(staleRows, s)
	}
	rows.Close()

	for _, s := range staleRows {
		if _, err := database.DB.Exec(ctx, `DELETE FROM nuzlocke_timeline_entries WHERE id = $1`, s.id); err != nil {
			log.Fatalf("Failed to delete stale timeline entry %q: %v", s.slug, err)
		}
		log.Printf("Pruned %s timeline entry %q (%s) — no longer in the seed file.", version, s.slug, s.name)
	}
}
