// cmd/seed_nuzlocke seeds the Nuzlocke reference timeline (locations with
// their encounter pools, bosses with their squads/movesets/level caps) from
// seeds/nuzlocke_platinum.json. That file is generated by
// backend/extract_nuzlocke_seed.js from the owner's design prototype
// (docs/design/hunt-prototype.dc.html) — never hand-edit the timeline data,
// re-run the extractor against the prototype instead.
//
// Idempotent like cmd/seed's seedMethods: nuzlocke_timeline_entries is
// upserted on (game_id, slug), never truncated, so timeline_entry_id stays
// stable across re-seeds — nuzlocke_encounters_logged and
// nuzlocke_boss_progress reference it and must not be orphaned by a re-seed
// (see migrations/013_add_nuzlocke.sql). A location's encounter pool and a
// boss's squad/moves are fully owned children of one timeline entry with no
// independent identity of their own, so those are simply replaced in full
// under the entry's stable id on every run.
package main

import (
	"context"
	"encoding/json"
	"log"
	"os"

	"github.com/casper/shinytracker/internal/database"
	"github.com/joho/godotenv"
)

type seedFile struct {
	Game    string      `json:"game"`
	Entries []seedEntry `json:"entries"`
}

type seedEntry struct {
	Slug       string        `json:"slug"`
	Kind       string        `json:"kind"` // "location" or "boss"
	SortOrder  int           `json:"sort_order"`
	Name       string        `json:"name"`
	Place      *string       `json:"place"`
	BossTitle  *string       `json:"boss_title"`
	LevelCap   *int          `json:"level_cap"`
	Encounters []int         `json:"encounters"` // location only: pokemon ids
	Squad      []seedBossMon `json:"squad"`      // boss only
}

type seedBossMon struct {
	PokemonID int        `json:"pokemon_id"`
	Level     int        `json:"level"`
	Ability   string     `json:"ability"`
	SortOrder int        `json:"sort_order"`
	Moves     []seedMove `json:"moves"`
}

type seedMove struct {
	Name      string `json:"name"`
	Type      string `json:"type"`
	Power     int    `json:"power"`
	SortOrder int    `json:"sort_order"`
}

var validKinds = map[string]bool{"location": true, "boss": true}

func main() {
	_ = godotenv.Load()

	if err := database.ConnectDB(); err != nil {
		log.Fatal("Failed to connect to database:", err)
	}
	defer database.CloseDB()

	seedPath := "seeds/nuzlocke_platinum.json"
	if len(os.Args) > 1 {
		seedPath = os.Args[1]
	}

	data, err := os.ReadFile(seedPath)
	if err != nil {
		log.Fatalf("Failed to read %s: %v", seedPath, err)
	}
	var sf seedFile
	if err := json.Unmarshal(data, &sf); err != nil {
		log.Fatalf("JSON parse error in %s: %v", seedPath, err)
	}

	ctx := context.Background()

	var gameID int
	if err := database.DB.QueryRow(ctx, "SELECT id FROM games WHERE title = $1", sf.Game).Scan(&gameID); err != nil {
		log.Fatalf("Failed to find game %q: %v", sf.Game, err)
	}

	currentSlugs := make([]string, 0, len(sf.Entries))
	for _, e := range sf.Entries {
		if !validKinds[e.Kind] {
			log.Fatalf("Entry %q has invalid kind %q (must be location or boss)", e.Slug, e.Kind)
		}
		if e.Slug == "" {
			log.Fatalf("Entry %q is missing its stable slug", e.Name)
		}

		var entryID int
		err := database.DB.QueryRow(ctx,
			`INSERT INTO nuzlocke_timeline_entries (game_id, slug, kind, name, sort_order, place, boss_title, level_cap)
			 VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
			 ON CONFLICT (game_id, slug) DO UPDATE SET
			     kind = EXCLUDED.kind,
			     name = EXCLUDED.name,
			     sort_order = EXCLUDED.sort_order,
			     place = EXCLUDED.place,
			     boss_title = EXCLUDED.boss_title,
			     level_cap = EXCLUDED.level_cap
			 RETURNING id`,
			gameID, e.Slug, e.Kind, e.Name, e.SortOrder, e.Place, e.BossTitle, e.LevelCap,
		).Scan(&entryID)
		if err != nil {
			log.Fatalf("Failed to upsert timeline entry %q: %v", e.Slug, err)
		}
		currentSlugs = append(currentSlugs, e.Slug)

		switch e.Kind {
		case "location":
			seedEncounterPool(ctx, entryID, e)
		case "boss":
			seedBossSquad(ctx, entryID, e)
		}
	}

	pruneRemovedEntries(ctx, gameID, currentSlugs)

	log.Printf("Seeded %d Nuzlocke timeline entries for %q.", len(sf.Entries), sf.Game)
}

// seedEncounterPool replaces the full encounter pool for one location entry.
// The pool has no identity of its own outside the entry it belongs to, so a
// full delete+reinsert under the entry's stable id is simpler than diffing
// and just as safe.
func seedEncounterPool(ctx context.Context, entryID int, e seedEntry) {
	if _, err := database.DB.Exec(ctx, `DELETE FROM nuzlocke_encounter_pool WHERE timeline_entry_id = $1`, entryID); err != nil {
		log.Fatalf("Failed to clear encounter pool for %q: %v", e.Slug, err)
	}
	for i, pokemonID := range e.Encounters {
		if _, err := database.DB.Exec(ctx,
			`INSERT INTO nuzlocke_encounter_pool (timeline_entry_id, pokemon_id, sort_order) VALUES ($1, $2, $3)`,
			entryID, pokemonID, i+1,
		); err != nil {
			log.Fatalf("Failed to insert encounter pool row for %q (pokemon %d): %v", e.Slug, pokemonID, err)
		}
	}
}

// seedBossSquad replaces a boss's full squad and movesets. Same
// delete+reinsert rationale as seedEncounterPool; boss_moves cascades off
// boss_pokemon so clearing the squad clears its moves too.
func seedBossSquad(ctx context.Context, entryID int, e seedEntry) {
	if _, err := database.DB.Exec(ctx, `DELETE FROM nuzlocke_boss_pokemon WHERE timeline_entry_id = $1`, entryID); err != nil {
		log.Fatalf("Failed to clear boss squad for %q: %v", e.Slug, err)
	}
	for _, sq := range e.Squad {
		var bossPokemonID int
		if err := database.DB.QueryRow(ctx,
			`INSERT INTO nuzlocke_boss_pokemon (timeline_entry_id, pokemon_id, level, ability, sort_order)
			 VALUES ($1, $2, $3, $4, $5) RETURNING id`,
			entryID, sq.PokemonID, sq.Level, sq.Ability, sq.SortOrder,
		).Scan(&bossPokemonID); err != nil {
			log.Fatalf("Failed to insert boss squad member for %q (pokemon %d): %v", e.Slug, sq.PokemonID, err)
		}
		for _, mv := range sq.Moves {
			if _, err := database.DB.Exec(ctx,
				`INSERT INTO nuzlocke_boss_moves (boss_pokemon_id, name, type, power, sort_order) VALUES ($1, $2, $3, $4, $5)`,
				bossPokemonID, mv.Name, mv.Type, mv.Power, mv.SortOrder,
			); err != nil {
				log.Fatalf("Failed to insert boss move %q for %q: %v", mv.Name, e.Slug, err)
			}
		}
	}
}

// pruneRemovedEntries deletes any timeline entry for this game whose slug is
// no longer present in the seed file. Mirrors cmd/seed's
// pruneRemovedMethods: nuzlocke_timeline_entries is no longer truncated each
// run, so a row dropped from the JSON would otherwise linger forever. Any
// nuzlocke_encounters_logged/nuzlocke_boss_progress row pointing at it is
// SET NULL (migrations/013_add_nuzlocke.sql), not deleted, so this can never
// destroy a user's run — but it is logged loudly all the same.
func pruneRemovedEntries(ctx context.Context, gameID int, currentSlugs []string) {
	rows, err := database.DB.Query(ctx,
		`SELECT id, slug, name FROM nuzlocke_timeline_entries WHERE game_id = $1 AND NOT (slug = ANY($2))`,
		gameID, currentSlugs)
	if err != nil {
		log.Fatal("Failed to query stale nuzlocke_timeline_entries: ", err)
	}
	type stale struct {
		id   int
		slug string
		name string
	}
	var staleRows []stale
	for rows.Next() {
		var s stale
		if err := rows.Scan(&s.id, &s.slug, &s.name); err != nil {
			rows.Close()
			log.Fatal("Failed to scan stale nuzlocke_timeline_entries row: ", err)
		}
		staleRows = append(staleRows, s)
	}
	rows.Close()

	for _, s := range staleRows {
		log.Printf("PRUNING nuzlocke_timeline_entries %q (id=%d, slug=%q): no longer present in the seed file. "+
			"Any run referencing it now has that entry set to NULL.", s.name, s.id, s.slug)
		if _, err := database.DB.Exec(ctx, `DELETE FROM nuzlocke_timeline_entries WHERE id = $1`, s.id); err != nil {
			log.Fatalf("Failed to prune nuzlocke_timeline_entries %q (id=%d): %v", s.name, s.id, err)
		}
	}
	if len(staleRows) > 0 {
		log.Printf("Pruned %d nuzlocke_timeline_entries row(s) removed from the seed file.", len(staleRows))
	}
}
